### ISSUE TITLE
Unicode character not correctly converted

### ISSUE THREAD

**Issue by RCatersels** [Erwin-t-Hoen/Flat-File-Importer#1]
Hello Erwin, 

This could be a setting issue but I tried both the UTF-8 and CP1252 file encoding settings and this made no difference.
When I import a csv file with for example 'één maand' it comes out in the database as ��n maand. I checked the hex code that is comming in (e9) so with the CP1252 it should come out if I am not mistaken as é. Any suggestions?

Regards,

Ronald

**Comment by Erwin-t-Hoen** [comment]
@RCatersels,

Just test this with the latest release 4.4.0 using één in the file and char encoding CP1252 and this results in één in my string field. Please try this in the 4.4.0 release and if this still comes out wrong the issue must be in the file that is being used and you could try to investigate the file's BOM e.g.
