### ISSUE TITLE
Module not working in Mendix 8.3.0

### ISSUE THREAD

**Issue by sjoerdbeljon** [Erwin-t-Hoen/Flat-File-Importer#10]
The module does not work in Mendix  8.3.0.61600 (build 61600)  in the log in the modeler it states that it can not create entity "Unable to create entity record1,2,3,4'

**Comment by Erwin-t-Hoen** [comment]
Have a look at the details as I just tested the current version in Mendix 8.3.0 and am able to import the data without issues.
Probably the file and the configuration mismatch.

**Comment by sjoerdbeljon** [comment]
@Erwin-t-Hoen  I forgot to update... It works now in 8.4.1. I've tried it with the same configuration and it did not work in 8.3.0 there was a problem with  committing multiple entities associated to the same autocommited object. This might have caused the issues. It works fine in 8.4.1, thanks!
