### ISSUE TITLE
Decimail datatype

### ISSUE THREAD

**Issue by Luch** [Erwin-t-Hoen/Flat-File-Importer#2]
Any plans to support the new Decimal datatype?

**Comment by Erwin-t-Hoen** [comment]
I already have a newer version that will allow decimal datatypes to be imported. Only need to find the time to do some further testing and publish it.

**Comment by Erwin-t-Hoen** [comment]
I found time :-)
The versions from 5.5.0 and up now support the decimal datatype as well.
