### ISSUE TITLE
Please update this awesome app for Mendix 6.8.1 or greater

### ISSUE THREAD

**Issue by hln98** [Erwin-t-Hoen/Flat-File-Importer#3]
Hello,

Please update this awesome app for Mendix 6.8 or greater.  We are trying to use it but it is not compatible with our current Mendix version 6.8.1

Thank you.

Hoang

**Comment by isamu-tanaka** [comment]
Mendix 7 does not support this module, yet.  However, an official document for Mendix 7 introduces this module.

**Comment by Erwin-t-Hoen** [comment]
New versions for Mx 5.18.0, 6.10.4 and 7.1.1 ahve been added to github and will be published in the appstore.
