### ISSUE TITLE
FileEncoding not used when using the internal queue

### ISSUE THREAD

**Issue by JeffreyDraaijer** [Erwin-t-Hoen/Flat-File-Importer#4]
I noticed that when using the internal queue the fileEncoding is not used on line 236 by the InputStreamReader. Can you explain why and/or update with the ,fileEncoding?

"BufferedReader br = new BufferedReader(new InputStreamReader(fstream, fileEncoding));"

**Comment by Erwin-t-Hoen** [comment]
Fixed in version 7.23.6

**Comment by Erwin-t-Hoen** [comment]
Fixed in release 7.23.6 now available
