### ISSUE TITLE
shared.java contains tryCommit = false causing rows with empty column values to be skipped in db commit

### ISSUE THREAD

**Issue by stephanbruijnis** [Erwin-t-Hoen/Flat-File-Importer#5]
With the cases for Float, Currency, Decimal etc.  the following code block seems to be inappropriate. When one or more trimmedColumnValues are empty the object is not committed to the database, because the variable tryCommit is set to false. This variable is used to add the new object to a commit list, any other values on the same row are not stored because of it.

`else 
tryCommit = false;
`

**Comment by tieniber** [comment]
Agreed - I feel simply allowing the value to be empty would be ok and expected in many cases.

**Comment by Erwin-t-Hoen** [comment]
Has been resolved already.
