### ISSUE TITLE
Delimiter and text indicator

### ISSUE THREAD

**Issue by sjoerdbeljon** [Erwin-t-Hoen/Flat-File-Importer#6]
I've configured the File Importer and importing works great. I have a file however with a | as delimiter and " "(double quotes) as text indicators. When configuring this and setting a text indicator e.g it does not remove the text indicator whilst importing.

**Comment by Erwin-t-Hoen** [comment]
Will be fixed in version 7.23.6

**Comment by Erwin-t-Hoen** [comment]
Fixed in release 7.23.6 now available
