### ISSUE TITLE
Export of interfaces with skipped columns

### ISSUE THREAD

**Issue by Hmrhatigan** [Erwin-t-Hoen/Flat-File-Importer#7]
The export of definitions with skipped columns was not working as the column and interface definitions were passing (empty) values to non-nillable fields, updating those fields within the xsd to nillable=true fixes this issue.

[InterfaceDefinitionUpdated.txt](https://github.com/Erwin-t-Hoen/Flat-File-Importer/files/2582422/InterfaceDefinitionUpdated.txt)

**Comment by Erwin-t-Hoen** [comment]
Thanks for the updated xsd this will be included in version 7.23.6

**Comment by Erwin-t-Hoen** [comment]
Fixed in release 7.23.6 now available
